### ISSUE TITLE
Ch 10: Test url rather than path

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#10]
Your mailer spec has `expect(mail.body.encoded).to match edit_friendship_path(user, friend)` but mail message usually has url rather than path. So I feel `expect(mail.body.encoded).to match edit_friendship_url(user, friend)` is better. (`edit_friendship_url` includes `edit_friendship_path`, though.)

In addition, such a test case usually requires `default_url_options` in `test.rb`. Beginners might get in trouble (like I used to).

**Comment by ruralocity** [comment]
Fixed for the next book update.
