### ISSUE TITLE
Ch 2: Where do you test a specific view in chapter 12?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#15]
In chapter 2, you wrote "That said, there are times when it makes sense to test a specific view. See chapter 12 for more details.", but I could not understand what you mean. In chapter 12, I am not sure which one is written about view test.

**Comment by ruralocity** [comment]
I deleted the work I'd done on unit testing views. I've removed the line from chapter 2 for the next update.
