### ISSUE TITLE
Ch 10: Sample code format is broken.

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#17]
In chapter 10, sample code format is broken. Here is my iBooks screen:

![screen shot 2014-10-14 at 5 38 35](https://cloud.githubusercontent.com/assets/1148320/4619777/01a2ba86-5319-11e4-98b1-3fd8626d5cd2.png)

**Comment by ruralocity** [comment]
This is fixed for the next release.
