### ISSUE TITLE
Ch 3, 'bin/rspec' is better than 'rspec'

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#2]
> Now, if we run RSpec from the command line again (via `rspec` or `bundle exec rspec`, depending on whether you installed the `rspec` binstub in the previous chapter) we see one passing example!

In the sentence above, you wrote "via `rspec` or `bundle exec rspec`" but I think "via `bin/rspec` or `bundle exec rspec`" would be better because readers can easily understand they are using the installed binstub.

**Comment by ruralocity** [comment]
I've fixed this and will include it in the next release.
