### ISSUE TITLE
Phone class should have attribute other than phone.

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#20]
Phone class has phone attribute. I think it could lead confusing.

E.g.

``` ruby
contact = Contact.find params[:id]
phones = contact.phones # Phone instances
phones = phones.map{|phone| phone.phone } # Phone attributes
```

It would be better if it has different attribute name. For example:

``` ruby
contact = Contact.find params[:id]
phones = contact.phones
phone_numbers = phones.map{|phone| phone.phone_number }
```

**Comment by ruralocity** [comment]
While I agree with you, I may leave this as-is. Changing it could cause a lot of other errors due to how the sample application builds up from branch to branch.

**Comment by JunichiIto** [comment]
Okay, I understand.
