### ISSUE TITLE
Ch 9: skip is preferable to pending

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#21]
As you know, `pending` behavior has been changed since RSpec 3. So the code below should use `skip` rather than `pending` in this context:

``` ruby
    it "loads a lot of data" do
      pending "no longer necessary"
      # your spec's code; it will not be run
    end
```

And I think it is worth mentioning about the difference between `skip` and `pending`.

**Comment by ruralocity** [comment]
I'd forgotten about this—I don't use skip/pending very often day-to-day. Fixed for the next release.
