### ISSUE TITLE
Ch 11: title_with_date should be helper method

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#23]
The implementation of `title_with_date` is view-specific, so it should be implemented as helper method rather than model instance method. And `I18n.l` is preferable to `strftime` for internationalization purpose. For example:

``` ruby
    module NewsReleasesHelper
      def title_with_date(news_release)
        "#{l news_release.released_on}: #{news_release.title}"
      end
    end
```

Other solution is using decorator gem like Draper. (It would be overkill here, though.)

**Comment by ruralocity** [comment]
I admit that the reason I put it in the model was to have an example for a model spec, and not have all the examples in this chapter be at the feature level. Do you have any suggestions for a better model spec example here?

**Comment by JunichiIto** [comment]
Mmm, that's difficult. I don't have no idea about it. Okay, I understood your intention. If I could find better example, I will let you know.
