### ISSUE TITLE
Ch 11: Generator config can be used to skip creating JS, SCSS and helper

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#24]
You might know, but generator config can be used to skip creating JS, SCSS and helper:

``` ruby
    config.generators do |g|
      # ...     
      g.assets false
      g.helper false
      g.javascripts false
      g.stylesheets false
    end
```

However, this is technique about Rails, not RSpec, so I am not sure if it is worth mentioning.

**Comment by ruralocity** [comment]
Fixed this for the next release. I'm not changing the sample code, but mentioned this in an aside.
