### ISSUE TITLE
Ch 10: have_http_status matcher exists

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#25]
In chapter 10, you suggest creating custom matcher called `have_status_code`, but I found the same matcher called `have_http_status` in rspec-rails.

https://www.relishapp.com/rspec/rspec-rails/v/3-1/docs/matchers/have-http-status-matcher#using-in-a-request-spec

**Comment by ruralocity** [comment]
I thought I read somewhere that this was either deprecated or private, but I guess not. Fixed for the next release.
