### ISSUE TITLE
More testing... : Rails Tutorial 3rd edition is different from previous editions.

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#26]
As you might know, Rails Tutorial 3rd edition is out now.

The news release says, it is using MiniTest and Lighter-weight testing approach:

http://news.railstutorial.org/rails_tutorial_3rd_ed_screencast_access

I have not read it yet, but the description in "More testing resources for Rails" might need to be changed.

**Comment by ruralocity** [comment]
I haven't read through the whole thing, but I really like his introduction to testing in general (see https://www.railstutorial.org/book/static_pages#aside-when_to_test). I've updated the description to reflect the change.
