### ISSUE TITLE
Ch 2. Cannot run bin/rspec 

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#27]
A reader reported `bin/rspec` cannot run in "Applying your database schema to test". He or she checked out 01_untested branch and found rspec binstub did not exist in bin directory:
https://github.com/everydayrails/rails-4-1-rspec-3-0/tree/01_untested/bin

Could you check it?

**Comment by ruralocity** [comment]
01_untested shouldn't have `bin/rspec` yet, but I've added it as an explicit step in chapter 2 for setup. It will be included in the next update.
