### ISSUE TITLE
Ch.9: About run_all_when_everything_filtered option

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#28]
As for chapter 9 - Tags, a reader commented it might be worth mentioning about run_all_when_everything_filtered option:

https://www.relishapp.com/rspec/rspec-core/v/3-1/docs/configuration/run-all-when-everything-filtered

With this option, you don't have to remove `config.filter_run focus: true`.

**Comment by ruralocity** [comment]
Good idea. I've added this for the next release.
