### ISSUE TITLE
Ch 3, worth mentioning about 'not_to' and 'to_not'

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#3]
I found you use `not_to` instead of `to_not` from RSpec 3 edition and I am wondering why.

But anyway I think it is worth mentioning about `not_to` and `to_not`. Readers should know they can use both. If there is any rule to determine which to use, I would like to know it.

**Comment by JunichiIto** [comment]
In chapter 5 and chapter 11, `to_not` still exists. Please grep and fix them for consistency.

**Comment by ruralocity** [comment]
I changed them to match RSpec's documentation more closely. I've updated the book for consistency and will update the example repo before releasing an update.
