### ISSUE TITLE
curly brackets not needed for FactoryGirl + Faker

### ISSUE THREAD

**Issue by duarme** [everydayrails/rails-4-1-rspec-3-0#31]
When you introduce Faker on page 54 there is this code example:

```
FactoryGirl.define do 
  factory :contact do
    firstname { Faker::Name.first_name }
    lastname { Faker::Name.last_name }
    email { Faker::Internet.email }
  end 
end
```

but I think the curly brackets aren't needed.

**Comment by duarme** [comment]
My bad: they are actually needed for unique values.

**Comment by ruralocity** [comment]
Yeah, as far as I know anything dynamic needs to be passed in as a block. I'm closing this but please re-open if you find otherwise.
