### ISSUE TITLE
Ch4, "is has a valid factory." exists

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#4]
In Simplifying our syntax section in chapter 4, the sample code is described as "is has a valid factory". It  should be "has a valid factory".

**Comment by ruralocity** [comment]
I've fixed this in the book and will update the sample source repo before releasing the next update.

**Comment by ruralocity** [comment]
I've fixed this in the repo and will push the update alongside the next book update.
