### ISSUE TITLE
Ch 3, spec_helper still exists

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#5]
> As you may be able to spot, we’re creating an outline of examples here to help us sort similar examples together. This makes for a more readable spec. Now let’s finish cleaning up our reorganized spec with the help of a before hook:

Sample code after the sentence above still require spec_helper. And I found some 'spec_helper's in other chapters. Please grep and fix them.

**Comment by ruralocity** [comment]
Corrected for the next release.
