### ISSUE TITLE
application.rb p. 17

### ISSUE THREAD

**Issue by tenzan** [everydayrails/rails-4-1-rspec-3-0#65]
It's written:

If you use the `scaffold generator` to add code to your application, you may want to consider this.

```
config.generators do |g|
   g.test_framework :rspec,
     fixtures: true,
     view_specs: false,
     helper_specs: false,
    routing_specs: false,
    controller_specs: true,
    request_specs: false
  g.fixture_replacement :factory_girl, dir: "spec/factories"
end
```

What if I don't use `scaffold generator` ? How should I change the above?

**Comment by ruralocity** [comment]
`config.generators` applies to all Rails generators, not just scaffold. So it depends on if you use any generators or not. For example, with the above configuration, the model generator would give you files for the model, the model spec, and a factory file.

If you don't use any generators, then it doesn't matter what you put in this config.

I recommend creating a new Rails app and experimenting with different settings and generators and see what works best for you.

**Comment by tenzan** [comment]
Thanks, Aaron.

I noticed when I run, for example, `rails g model post title body`, it creates factories when I have settings in `application.rb` in advance, so I can be useful.
