### ISSUE TITLE
Ch 2, need to install Launchy explicitly?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#7]
As you mentioned in chapter 8, Launchy is installed with Capybara. So you can remove it from Gemfile. Actually I have never added Launchy to Gemfile explicitly.

**Comment by ruralocity** [comment]
Does launchy work for you when not explicitly installed? I always get "Please install the launchy gem to open the file automatically." if I'm not explicit about it.

**Comment by JunichiIto** [comment]
You are right. I confirmed this application needs to install Launchy explicitly. In my case, some other gems seem to install it via their dependencies.
