### ISSUE TITLE
Ch 9: "specify { should ..." is not readable

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#8]
In chapter 9, you wrote `specify { should be_named 'John Doe' }` but it is not readable. It would be better to write as `it { is_expected.to be_named 'John Doe' }`. Other sample codes like `it { should ... }` should be changed to `it { is_expected.to ...}` too, because you can write without "should" with RSpec 3.

**Comment by ruralocity** [comment]
I've fixed this in the book and will update the code samples before the next release.

**Comment by JunichiIto** [comment]
As you might know, in chapter 11, codes like `it { should validate_presence_of :released_on }` exist. It should be `it { is_expected.to validate_presence_of :released_on }` too.

**Comment by ruralocity** [comment]
Fixed for chapter 11 as well.
