### ISSUE TITLE
Spring is not used in binstubs.

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rails-4-1-rspec-3-0#9]
In chapater 9, you introduced Guard + Spring, but in branches for chapter 9, 11 and master, `bin/rspec` does not use Spring. It is very confusing.

In addition, I think `bin/rails` and `bin/rake` should use Spring from the start, because this is Rails 4.1 application.

**Comment by ruralocity** [comment]
This is ready for the next release.
